Repository Team-HMH/HMH-iOS, pull requests merged in 2024-01, with the labels that each got.

#8 Feat [#7] 커스텀 HMHNavigationBar 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Literal.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ic_back.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ic_back.imageset/ic_back.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ic_back.imageset/ic_back@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ic_back.imageset/ic_back@3x.png
  HMH_iOS/HMH_iOS/Presentation/Common/UIComponets/D.swift
  HMH_iOS/HMH_iOS/Presentation/Common/UIComponets/HMHNavigationBar.swift
Labels: 😎선우, 🌈 feat, 🎨 style

#10 Feat [#9] 커스텀 버튼 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Presentation/Common/UIComponets/HMHSelectButton.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingButton.swift
Labels: 😎선우, 🌈 feat, 🎨 style

#12 Fea [/#5] App Picker SwiftUI button 구현
  HMH_iOS/DeviceMonitor/DeviceActivityMonitorExtension.swift
  HMH_iOS/DeviceMonitor/DeviceMonitor.entitlements
  HMH_iOS/DeviceMonitor/Info.plist
  HMH_iOS/DeviceReport/DeviceReport.entitlements
  HMH_iOS/DeviceReport/DeviceReport.swift
  HMH_iOS/DeviceReport/Info.plist
  HMH_iOS/DeviceReport/TotalActivityReport.swift
  HMH_iOS/DeviceReport/TotalActivityView.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/SupportingFiles/AppBlock/BlockingApplicationModel.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/AppBlock/SelectedBlocker.swift
  HMH_iOS/HMH_iOS/HMH_iOS.entitlements
  HMH_iOS/HMH_iOS/Presentation/Common/SwiftUIView/HMHAppSelectButtonView.swift
Labels: 🐰지희, 🌈 feat

#13 Feat [#6] customTabbar 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/first_active.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/first_active.imageset/first_active.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/first_default.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/first_default.imageset/first_default.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/second_active.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/second_active.imageset/second_active.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/second_default.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/second_default.imageset/second_default.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/third_active.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/third_active.imageset/third_active.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/third_default.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/third_default.imageset/third_default.svg
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/ChanllengeCells.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Models/ChanllengeModels.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/ChanllengeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChanllengeViews.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomTabbar/TabBarController.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Cells/MyPageCells.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Models/MyPageModels.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Views/MyPageViews.swift
Labels: 🙊보연, 🌈 feat, 🎨 style

#15 Feat [#11] CreateChallenge - pickerView 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Presentation/Common/CustomTabbar/TabBarController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/Views/SpecificTimePickerView.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/Views/TotalTimePickerView.swift
Labels: 😎선우, 🌈 feat

#20 Feat [#16] OnboardingProgressView 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingProgressView.swift
Labels: 😎선우, 🌈 feat

#22 Feat [#21] OnboardingSwipeView 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingSwipeView.swift
Labels: 😎선우, 🌈 feat

#23 Feat [#18] CustomAlertView 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Global/Protocols/AlertDelegate.swift
  HMH_iOS/HMH_iOS/Global/Protocols/H.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/AlertViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/CustomAlertButton.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/HMHLogoutAlert.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/HMHQuitAlert.swift
Labels: 🙊보연, 🌈 feat, 🎨 style

#30 Fix[#24] tabbar 기기대응
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challengEnabled.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challengEnabled.imageset/challengEnabled.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challengeDisabled.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challengeDisabled.imageset/challengeDisabled.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/homeDisabled.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/homeDisabled.imageset/homeDisabled.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/homeEnabled.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/homeEnabled.imageset/homeEnabled.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/mypageDisabled.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/mypageDisabled.imageset/mypageDisabled.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/mypageEnabled.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/mypageEnabled.imageset/mypageEnabled.svg
  HMH_iOS/HMH_iOS/Presentation/Common/CustomTabbar/TabBarController.swift
Labels: 🙊보연, 🐞fix

#32 Feat [#29] 나의 챌린지 뷰 Footer Button 완성
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/Minus_XL.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/Minus_XL.imageset/Minus_XL.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/Minus_XL.imageset/Minus_XL@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/Minus_XL.imageset/Minus_XL@3x.png
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/AppListCollectionViewCell.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/AppAddCollectionReusableView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/GrayBackgroundView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/SwiftUIView/AppAddButtonView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/ChallengeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
Labels: 🐰지희, 🌈 feat

#33 Feat [#28] onboardingbaseViewController 구현 및 프로그래스바 방식 수정
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ProgressBarManager.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/OnboardingBaseViewControllers.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingButton.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingProgressView.swift
Labels: 😎선우, 🌈 feat

#38 Fix [#37] 폰빌드 오류 해결
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
Labels: 🐰지희, 🐞fix

#39 Feat [#34] 온보딩 survey 관련 뷰 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Presentation/Common/UIComponets/HMHNavigationBar.swift
  HMH_iOS/HMH_iOS/Presentation/Common/UIComponets/HMHSelectButton.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Models/SignInModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/OnboardingBaseViewControllers.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/ProblemSurveyViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/TimeSurveyViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingButton.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/SurveyView.swift
Labels: 😎선우, 🌈 feat

#41 Feat [#40] splash&로그인 UI 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewControllers/LoginViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingSwipeView.swift
  HMH_iOS/HMH_iOS/Presentation/Splash/ViewControllers/SplashViewController.swift
Labels: 😎선우, 🌈 feat

#50 Feat [#49] SignInCompleteViewController 회원가입 완료 화
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/SignInCompleteViewController.swift
Labels: 😎선우, 🌈 feat

#55 [Set [#54] Lottie Package 추가
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMH_iOS/HMH_iOS/Presentation/Splash/ViewControllers/SplashViewController.swift
Labels: 🐰지희, ⚒️ set

#52 Feat [#51] 스크린 타임 모니터링 앱 삭제 UI 로직
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/AppListCollectionViewCell.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/AppCollectionReusableView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/ChallengeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
Labels: 🐰지희, 🌈 feat

#56 Set [#53] 네트워크 환경 세팅
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Info.plist
  HMH_iOS/HMH_iOS/Network/Base/AuthInterceptor.swift
  HMH_iOS/HMH_iOS/Network/Base/BaseModel.swift
  HMH_iOS/HMH_iOS/Network/Base/BaseTargetType.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/CreateChallengeRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/CreateChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Network/Foundation/NetworkHelper.swift
  HMH_iOS/HMH_iOS/Network/Foundation/NetworkRequest.swift
  HMH_iOS/HMH_iOS/Network/Router/ChallengeRouter.swift
  HMH_iOS/HMH_iOS/Network/Service/Providers.swift
  HMH_iOS/HMH_iOS/Network/Service/WeatherTarget.swift
Labels: 🐰지희, ⚒️ set

#57 Set [#46] apple login 기초 세팅
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/User/UserDefaultWrapper.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/User/UserManager.swift
  HMH_iOS/HMH_iOS/HMH_iOS.entitlements
  HMH_iOS/HMH_iOS/Presentation/Login/ViewControllers/LoginViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Models/SignInModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/OnboardingBaseViewControllers.swift
Labels: 😎선우, ⚒️ set

#59 Feat[#44] homeViewUI 구현과 분기처리
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Cells/AppUsingProgressViewCell.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Cells/BlackHoleImageCell.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Cells/MyGoalTimeCell.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Models/AppUsingTimeModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/HMHHomeView.swift
Labels: 🙊보연, 🌈 feat, 🎨 style

#63 Fix [#62] 루트 뷰 컨트롤러 이동 수정
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Global/Extension/UIViewController+.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomTabbar/TabBarController.swift
  HMH_iOS/HMH_iOS/Presentation/Common/UIComponets/HMHNavigationBar.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewControllers/LoginViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/SignInCompleteViewController.swift
Labels: 😎선우, 🐞fix

#64 Set [#60] 에셋 추가
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/blackhole_fail.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/blackhole_fail.imageset/blackhole_fail.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/blackhole_fail.imageset/blackhole_fail@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/blackhole_fail.imageset/blackhole_fail@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challenge_ic_fail.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challenge_ic_fail.imageset/challenge_ic_fail.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challenge_ic_fail.imageset/challenge_ic_fail@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challenge_ic_fail.imageset/challenge_ic_fail@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challenge_ic_success.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challenge_ic_success.imageset/challenge_ic_success.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challenge_ic_success.imageset/challenge_ic_success@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/challenge_ic_success.imageset/challenge_ic_success@3x.png
Labels: 🐰지희, ⚒️ set

#65 Feat[#61] myPageLogoutAndQuit 뷰 연결
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/AlertViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/CustomAlertButton.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/HMHLogoutAlert.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/HMHQuitAlert.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Cells/LogoutAndQuitFooterView.swift
Labels: 🙊보연, 🌈 feat

#69 Fix [#36] 목표 시간 설정뷰
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/GoalTimeSelectView.swift
Labels: 🐰지희, 🐞fix

#71 Feat [#68] MyPageInfo 구현
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Views/MyPageView.swift
Labels: 🙊보연, 🌈 feat

#72 Feat [#58] SignUpManager, 이미지 추가
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_1.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_1.imageset/img_ios_onboarding_1.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_1.imageset/img_ios_onboarding_1@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_1.imageset/img_ios_onboarding_1@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_2.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_2.imageset/img_ios_onboarding_2.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_2.imageset/img_ios_onboarding_2@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_2.imageset/img_ios_onboarding_2@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_3.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_3.imageset/img_ios_onboarding_3.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_3.imageset/img_ios_onboarding_3@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_onboarding_3.imageset/img_ios_onboarding_3@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_signUp.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_signUp.imageset/img_ios_signUp.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_signUp.imageset/img_ios_signUp@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_signUp.imageset/img_ios_signUp@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_splash.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_splash.imageset/ios_splash.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_splash.imageset/ios_splash@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_splash.imageset/ios_splash@3x.png
  HMH_iOS/HMH_iOS/Info.plist
  HMH_iOS/HMH_iOS/Presentation/Common/UIComponets/HMHSelectButton.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/ApprovePermisionController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/SelectPeriodController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/SelectTotalTimeController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/Views/HMHTimePickerView.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewControllers/LoginViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Models/SignInModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Models/SignUpManager.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/ProblemSurveyViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/SignInCompleteViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/TimeSurveyViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingSwipeView.swift
  HMH_iOS/HMH_iOS/Presentation/Splash/ViewControllers/SplashViewController.swift
Labels: 😎선우, 🌈 feat

#76 Network [#67] 마이페이지 UserAPI 연결
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Network/Base/NetworkProvider.swift
  HMH_iOS/HMH_iOS/Network/DTO/MyPageModel/GetUserDataResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Router/MyPageRouter.swift
  HMH_iOS/HMH_iOS/Network/Service/Providers.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Cells/UserPointHeaderView.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Views/MyPageView.swift
Labels: 🙊보연, 📡 network

#78 Set [#77] 이미지 에셋 추가
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_add_new_challenge_img.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_add_new_challenge_img.imageset/ios_add_new_challenge_img.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_add_new_challenge_img.imageset/ios_add_new_challenge_img@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_add_new_challenge_img.imageset/ios_add_new_challenge_img@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_challenge_alert_img.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_challenge_alert_img.imageset/ios_challenge_alert_img.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_challenge_alert_img.imageset/ios_challenge_alert_img@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_challenge_alert_img.imageset/ios_challenge_alert_img@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_limit_time_img.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_limit_time_img.imageset/ios_limit_time_img.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_limit_time_img.imageset/ios_limit_time_img@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_limit_time_img.imageset/ios_limit_time_img@3x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_profil_image.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_profil_image.imageset/ios_profil_image.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_sevenDays_challenge_img.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_sevenDays_challenge_img.imageset/ios_sevenDays_challenge_img.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_sevenDays_challenge_img.imageset/ios_sevenDays_challenge_img@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_sevenDays_challenge_img.imageset/ios_sevenDays_challenge_img@3x.png
Labels: 🙊보연, ⚒️ set

#79 Feat [#70] 권한 허용
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Global/Extension/UIApplication+.swift
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/AppBlock/ScreenTime.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/AppBlock/requestPermision.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/ChallengeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomTabbar/TabBarController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/ApprovePermisionController.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/ViewControllers/MyPageViewController.swift
Labels: 🐰지희, 🌈 feat

#83 Network [#75] 회원 가입 & 토큰 리프레시 API 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/User/UserManager.swift
  HMH_iOS/HMH_iOS/Network/Base/BaseTargetType.swift
  HMH_iOS/HMH_iOS/Network/Base/NetworkProvider.swift
  HMH_iOS/HMH_iOS/Network/DTO/AuthModel/RefreshTokenResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/AuthModel/SignUpRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/AuthModel/SignUpResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/AuthModel/SocialLoginResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Network/Router/AuthRouter.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/ApprovePermisionController.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewControllers/LoginViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Models/SignUpManager.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/TimeSurveyViewController.swift
Labels: 😎선우, 📡 network

#85 Network [#84] 회원 탈퇴 & 로그아웃 API 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/User/UserManager.swift
  HMH_iOS/HMH_iOS/Network/Base/NetworkProvider.swift
  HMH_iOS/HMH_iOS/Network/DTO/AuthModel/LogoutResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/AuthModel/RevokeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/CreateChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Network/Router/AuthRouter.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/AlertViewController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/ApprovePermisionController.swift
  HMH_iOS/HMH_iOS/Presentation/Splash/ViewControllers/SplashViewController.swift
Labels: 😎선우, 📡 network

#87 Feat [#80] 잠금 화면 뷰 구현 완료
  HMH_iOS/DeviceMonitor/HMHMonitorExtension.swift
  HMH_iOS/DeviceReport/ActivityReport.swift
  HMH_iOS/DeviceReport/DeviceReport.swift
  HMH_iOS/DeviceReport/TotalActivityReport.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Application/AppDelegate.swift
  HMH_iOS/HMH_iOS/Global/Extension/UserDefault+.swift
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/HMH_iOS.entitlements
  HMH_iOS/HMH_iOS/Presentation/Challenge/SwiftUIView/AppAddButtonView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/SwiftUIView/SwiftUIView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/AlertViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/HMHPushAlert.swift
  HMH_iOS/ShiledAction/ShieldActionExtension.swift
  HMH_iOS/ShiledConfig/Assets.xcassets/Contents.json
  HMH_iOS/ShiledConfig/Assets.xcassets/ios_limit_time_img.imageset/Contents.json
  HMH_iOS/ShiledConfig/Assets.xcassets/ios_limit_time_img.imageset/img_ios_limit.png
  HMH_iOS/ShiledConfig/Assets.xcassets/ios_limit_time_img.imageset/img_ios_limit@2x.png
  HMH_iOS/ShiledConfig/Assets.xcassets/ios_limit_time_img.imageset/img_ios_limit@3x.png
  HMH_iOS/ShiledConfig/ShieldConfigurationExtension.swift
Labels: 🐰지희, 🌈 feat

#88 Network [#82] interceptor 구현 완료
  HMH_iOS/HMH_iOS/Network/Base/AuthInterceptor.swift
  HMH_iOS/HMH_iOS/Network/Base/BaseTargetType.swift
  HMH_iOS/HMH_iOS/Network/Base/NetworkProvider.swift
  HMH_iOS/HMH_iOS/Network/Router/MyPageRouter.swift
  HMH_iOS/HMH_iOS/Network/Service/Providers.swift
Labels: 🐰지희, 📡 network

#90 Feat [#81] HomeView Video 추가
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Extension/TimeCalculate.swift
  HMH_iOS/HMH_iOS/Global/Handler/VideoHandler.swift
  HMH_iOS/HMH_iOS/Global/Resources/Videos/1StepBlackHole.mp4
  HMH_iOS/HMH_iOS/Global/Resources/Videos/2StepBlackHole.mp4
  HMH_iOS/HMH_iOS/Global/Resources/Videos/3StepBlackHole.mp4
  HMH_iOS/HMH_iOS/Global/Resources/Videos/4StepBlackHole.mp4
  HMH_iOS/HMH_iOS/Network/Router/MyPageRouter.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Cells/AppUsingProgressViewCell.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Cells/BlackHoleImageCell.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Cells/MyGoalTimeCell.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Models/AppUsingTimeModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Models/BlackHoleVideoDataModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Models/HomeViewTotalDataModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Models/TotalAppUsingTimeDataModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/HMHHomeView.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/VideoView.swift
Labels: 🙊보연, 🌈 feat

#92 Network [#89] 챌린지 관련 서버 통신
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Extension/UIApplication+.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/AppBlock/requestPermision.swift
  HMH_iOS/HMH_iOS/Network/Base/NetworkProvider.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/AddAppRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/AddAppResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/DeleteAppRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/EmptyResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/GetChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/HomeChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/MidnightRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/Router/AuthRouter.swift
  HMH_iOS/HMH_iOS/Network/Router/ChallengeRouter.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/GoalTimeSelectViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Common/SwiftUIView/HMHAppSelectButtonView.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/AppSelectViewController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/ApprovePermisionController.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/OnboardingGoalTimeViewController.swift
Labels: 🐰지희, 🌈 feat, 📡 network

#97 Fix [#96] MyPage 프로필 이미지 변경
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_profil_image.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_profil_image.imageset/ios_profil_image.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_profil_image.imageset/ios_profil_image.svg
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_profil_image.imageset/ios_profil_image@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/ios_profil_image.imageset/ios_profil_image@3x.png
  HMH_iOS/HMH_iOS/Presentation/MyPage/Cells/UserPointHeaderView.swift
Labels: 🙊보연, 🐞fix

#98 Fix [#91] MyPage 서버 통신 중복 수정
  HMH_iOS/HMH_iOS/Presentation/MyPage/Cells/UserPointHeaderView.swift
Labels: 🙊보연, 🐞fix, 📡 network

#101 Fix [#94] picker view 관련 ms값 가져오기 구현
  HMH_iOS/HMH_iOS/Application/SceneDelegate.swift
  HMH_iOS/HMH_iOS/Global/Extension/TimeCalculate.swift
  HMH_iOS/HMH_iOS/Global/SupportingFiles/User/UserManager.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/GoalTimeSelectViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/GoalTimeSelectView.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/AppSelectViewController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/CreatePeriodController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/CreateTotalTimeController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/SelectPeriodController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/SelectTotalTimeController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/Views/HMHTimePickerView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/OnboardingGoalTimeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/TimeSurveyViewController.swift
Labels: 😎선우, 🐞fix

#103 Feat [#102] Challenge 화면 챌린지 생성 경우 구현
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_14.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_14.imageset/img_ios_14.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_14.imageset/img_ios_14@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_ios_14.imageset/img_ios_14@3x.png
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/AppAddCollectionReusableView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/GrayBackgroundView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/TitleCollectionReusableView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/ChallengeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/CreateTotalTimeController.swift
Labels: 😎선우, 🌈 feat

#106 Fix [#102] 네비게이션 바 레이아웃 수정
  HMH_iOS/HMH_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 🙊보연, 🐞fix

#107 Fix [#104] Challenge뷰 UI 수정
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Global/Literals/String/String.swift
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_iOS_unselected.imageset/Contents.json
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_iOS_unselected.imageset/img_iOS_unselected.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_iOS_unselected.imageset/img_iOS_unselected@2x.png
  HMH_iOS/HMH_iOS/Global/Resources/Assets.xcassets/img_iOS_unselected.imageset/img_iOS_unselected@3x.png
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/DateCollectionViewCell.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/GrayBackgroundView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/TitleCollectionReusableView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/ChallengeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/HMHQuitAlert.swift
  HMH_iOS/HMH_iOS/Presentation/Common/CustomTabbar/TabBarController.swift
  HMH_iOS/HMH_iOS/Presentation/CreateChallenge/ViewControllers/SelectPeriodController.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewControllers/OnboardingGoalTimeViewController.swift
Labels: 😎선우, 🐞fix

#111 [Feat/#110] Alert - 삭제 API 적용
  HMH_iOS/HMH_iOS/Presentation/Common/CustomAlert/AlertViewController.swift
Labels: 😎선우, 🌈 feat

#113 [Fix/#112] Challenge - 레이아웃 수정
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/GrayBackgroundView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/TitleCollectionReusableView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
Labels: 😎선우, 🐞fix

#116 Network [#99] HomeViewNetwork
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMH_iOS/HMH_iOS/Global/Extension/UIImage+.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/GetDummyResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/GetHomeChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Router/ChallengeRouter.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Cells/AppUsingProgressViewCell.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Cells/MyGoalTimeCell.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Models/AppUsingTimeModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Models/HomeViewTotalDataModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Models/TotalAppUsingTimeDataModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewControllers/HomeViewController.swift
Labels: 🙊보연, 📡 network

#118 Network [#100] challengeView Network 연결
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS.xcodeproj/xcshareddata/xcschemes/DeviceMonitor.xcscheme
  HMH_iOS/HMH_iOS.xcodeproj/xcshareddata/xcschemes/DeviceReport.xcscheme
  HMH_iOS/HMH_iOS.xcodeproj/xcshareddata/xcschemes/HMH_iOS.xcscheme
  HMH_iOS/HMH_iOS.xcodeproj/xcshareddata/xcschemes/ShiledAction.xcscheme
  HMH_iOS/HMH_iOS.xcodeproj/xcshareddata/xcschemes/ShiledConfig.xcscheme
  HMH_iOS/HMH_iOS/Global/Literals/Literal/Image.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/GrayBackgroundView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/HeaderFooterView/TitleCollectionReusableView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/ChallengeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
Labels: 🐰지희, 📡 network

#124 Feat [#123] 데모데이용 앱
  HMH_iOS/HMH_iOS/Network/DTO/ChallengeModel/GetDummyResponseDTO.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Cells/AppListCollectionViewCell.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Models/ChanllengeModels.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewControllers/ChallengeViewController.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
Labels: 🐰지희, 🌈 feat, 📡 network
